### ISSUE TITLE
Get a shorter URL for SAW

### ISSUE THREAD

**Issue by zee-em** [saw-comics-gnv/planning#14]
GOAL: get a shortened SAW website URL, to make our lives easier. sawcomics.org is desired.

- [x] @mmmaxine set this up with GoDaddy. 

Don can help answer questions if needed :)

**Comment by zee-em** [comment]
@mmmaxine thanks for doing this! 
@hutchowen @MelissaIuliano @graphicstyle7 @no-carrier FYI you can now use and share 
sawcomics.org freely, it redirects to the existing sequentialartistsworkshop.org site. 
YAY!

**Comment by hutchowen** [comment]
Hey I thought I emailed this out, but it didn't go out... Pasting below.

[OH CRAP THOUGHT THIS SENT YESTERDAY]

Hey guys (especially maybe Deanna, who knows most about this?)

Our current online courses are at sequentialartistsworkshop.thinkific.com , so it's on the thinkific site. I know with our plan we can use our domain, etc, but is it possible to set up a subdomain to point there? 

Like onlinecourses.sawcomics.org for instance?

I know we can do this at Teachable see screenshots, looks like at Thinkific, too.

How hard is this and should this be and can we plan for it sooner rather than later on the squarespace end?

If not, can someone advise a good URL to buy for our online site?
![screen shot 2017-08-03 at 7 56 01 pm](https://user-images.githubusercontent.com/29961063/28986407-db24c134-7934-11e7-9f55-f005b252406d.png)
![screen shot 2017-08-03 at 7 59 10 pm](https://user-images.githubusercontent.com/29961063/28986408-db28b1c2-7934-11e7-9322-edd9e0e57df8.png)

**Comment by mmmaxine** [comment]
I don't see any reason not to do this—it's probably pretty easy. Can you
send me that Thinkific page where you got the screenshots from?

Also let's brainstorm something more succinct than
onlinecourses.sawcomics.org  ...

learn.sawcomics.org
courses.sawcomics.org
studyonline.sawcomics.org
onlineclass.sawcomics.org
            .sawcomics.org  [add your own ideas here]

**Comment by hutchowen** [comment]
how about either 
learn
or 
online

and  the page was just help on thinkific.com or even "features" or something. Github is public, right? I'll text you the log in if you want it

**Comment by mmmaxine** [comment]
I have the log in already! I'll look into it today!

**Comment by mmmaxine** [comment]
Donzo!

http://learn.sawcomics.org/ = short URL for *ONLINE CLASSES*

sawcomics.org/ <http://learn.sawcomics.org/> = short URL for everything
else --- it redirects to sequentialartistsworkshop.org/wordpress/

**Comment by hutchowen** [comment]
GREAT!

**Comment by hutchowen** [comment]
THANK YOU MAXINE.

So I reopened this, just to make sure we address some issues, that are probably fine. Namely SUMO pop-ups that have been set-up at the other URL, also, might want to go into Mailchimp and change all links (ay-yi-yi-) etc.

No hurry, probably, but this is cool, thanks so much

**Comment by mmmaxine** [comment]
You're welcome! Can you go into detail about this (and ideally put the
tasks into Github)? Are you talking about the Sumo pop ups on thinkific
(cuz they still work when I go to learn.sawcomics.org) or on the website?
And what Mailchimp things are you concerned about?

 We'll set up new pop-ups natively in Squarespace,

**Comment by hutchowen** [comment]
Um, yeah, I just want to double check we have the right pop-ups still working. 

Right now we have a global one (SAW COMICS) but then different ones for COMICS FOR WRITERS, ALIZA's CLASS and maybe one other? (SAW COMICS is turned OFF at these URLS) Also a few inner pages. I just want to double check they are still working, and I guess if anyone handles the keys ever, we will have to maintain the thinkific URLS because that presumably will work in both places where SAWCOMICS URLs won't (not that important yet.)

As far as mailchimp, we have LOTS of links in the automations. All go to the thinkific URLs, which again is fine, but if we're going to standardize that, we'll have to go in there and replace eventually.

And I haven't figured out GITHUB enough to make TASKS, I'm SORRY!!!!)) 🥇

**Comment by mmmaxine** [comment]
Hmm... Sounds like another GitHub lesson is needed!

As long as the links are embedded like this,
<http://learn.sawcomics.org/courses/every-picture-tells-a-story> I don't
think it's an issue to have mailchimp still link to the sequential[ect].
thinkific.com.

You're right about the pop ups: in the course pages that are at
learn.sawcomics.org/[class] the UNIVERSAL SAW pop up comes up, not the
unique pup ups.

**Comment by mmmaxine** [comment]
@hutchowen have you taken care of the Sumo pop ups or should I delve into this?

**Comment by hutchowen** [comment]
I think we should plan order of operations. Sumo only has to happen once we
start advertising online site with new url.

It's an short process to redo those pop-ups, maybe less than an hour, but
method might not be obvious.

I'd rather address current course outreach  (to interested people, people
in free trials, etc) before Sept 5

T
